Repository LemmyNet/lemmy, pull requests merged in 2024-09, with the labels that each got.

#4542 Remove nonstandard field `expires` from apub block activity (ref #2316)
  crates/apub/assets/lemmy/activities/block/block_user.json
  crates/apub/assets/lemmy/activities/block/undo_block_user.json
  crates/apub/src/activities/block/block_user.rs
  crates/apub/src/activities/block/undo_block_user.rs
  crates/apub/src/protocol/activities/block/block_user.rs
Labels: breaking change

#4890 Remove pointless local_user_id from LocalUserVoteDisplayMode
  crates/db_schema/src/source/local_user_vote_display_mode.rs
Labels: breaking change

#4888 Changing list_logins to return a ListLoginsResponse object.
  crates/api/src/local_user/list_logins.rs
  crates/api_common/src/person.rs
Labels: breaking change

#4741 Remove opentelemetry
  .woodpecker.yml
  Cargo.lock
  Cargo.toml
  crates/db_schema/src/schema_setup.rs
  crates/utils/Cargo.toml
  crates/utils/src/error.rs
  src/lib.rs
  src/main.rs
  src/root_span_builder.rs
  src/telemetry.rs
Labels: breaking change

#4841 Remove pointless block_views.
  crates/api_common/src/site.rs
  crates/api_crud/src/site/read.rs
  crates/db_schema/src/impls/community_block.rs
  crates/db_schema/src/impls/instance_block.rs
  crates/db_schema/src/impls/person_block.rs
  crates/db_views_actor/src/community_block_view.rs
  crates/db_views_actor/src/instance_block_view.rs
  crates/db_views_actor/src/lib.rs
  crates/db_views_actor/src/person_block_view.rs
  crates/db_views_actor/src/structs.rs
Labels: area: api, breaking change

#5017 Remove enable nsfw
  crates/api/src/local_user/generate_totp_secret.rs
  crates/api/src/local_user/login.rs
  crates/api/src/local_user/reset_password.rs
  crates/api/src/local_user/save_settings.rs
  crates/api/src/local_user/verify_email.rs
  crates/api/src/site/federated_instances.rs
  crates/api/src/site/leave_admin.rs
  crates/api_common/src/request.rs
  crates/api_common/src/utils.rs
  crates/api_crud/src/community/create.rs
  crates/api_crud/src/community/list.rs
  crates/api_crud/src/post/create.rs
  crates/api_crud/src/post/read.rs
  crates/api_crud/src/post/update.rs
  crates/api_crud/src/site/create.rs
  crates/api_crud/src/site/read.rs
  crates/api_crud/src/site/update.rs
  crates/api_crud/src/user/create.rs
  crates/apub/src/activities/block/mod.rs
  crates/apub/src/api/list_posts.rs
  crates/apub/src/api/read_person.rs
  crates/apub/src/api/search.rs
  crates/apub/src/collections/community_outbox.rs
  crates/apub/src/http/site.rs
  crates/apub/src/objects/post.rs
  crates/db_schema/src/impls/site.rs
  crates/db_schema/src/schema.rs
  crates/db_schema/src/source/local_site.rs
  crates/db_views/src/site_view.rs
  crates/routes/src/feeds.rs
  crates/routes/src/nodeinfo.rs
  migrations/2024-09-12-130204_drop-enable-nsfw/down.sql
  migrations/2024-09-12-130204_drop-enable-nsfw/up.sql
  src/code_migrations.rs
  src/lib.rs
Labels: breaking change

#4881 SSO Support
  Cargo.lock
  crates/api/src/local_user/change_password.rs
  crates/api/src/local_user/login.rs
  crates/api/src/local_user/mod.rs
  crates/api/src/local_user/reset_password.rs
  crates/api/src/site/leave_admin.rs
  crates/api_common/src/lib.rs
  crates/api_common/src/oauth_provider.rs
  crates/api_common/src/request.rs
  crates/api_common/src/site.rs
  crates/api_common/src/utils.rs
  crates/api_crud/Cargo.toml
  crates/api_crud/src/lib.rs
  crates/api_crud/src/oauth_provider/create.rs
  crates/api_crud/src/oauth_provider/delete.rs
  crates/api_crud/src/oauth_provider/mod.rs
  crates/api_crud/src/oauth_provider/update.rs
  crates/api_crud/src/site/create.rs
  crates/api_crud/src/site/read.rs
  crates/api_crud/src/site/update.rs
  crates/api_crud/src/user/create.rs
  crates/api_crud/src/user/delete.rs
  crates/db_schema/src/impls/local_user.rs
  crates/db_schema/src/impls/mod.rs
  crates/db_schema/src/impls/oauth_account.rs
  crates/db_schema/src/impls/oauth_provider.rs
  crates/db_schema/src/impls/person.rs
  crates/db_schema/src/newtypes.rs
  crates/db_schema/src/schema.rs
  crates/db_schema/src/source/local_site.rs
  crates/db_schema/src/source/local_user.rs
  crates/db_schema/src/source/mod.rs
  crates/db_schema/src/source/oauth_account.rs
  crates/db_schema/src/source/oauth_provider.rs
  crates/db_schema/src/utils.rs
  crates/db_views/src/local_user_view.rs
  crates/routes/src/images.rs
  crates/utils/src/error.rs
  migrations/2024-09-16-174833_create_oauth_provider/down.sql
  migrations/2024-09-16-174833_create_oauth_provider/up.sql
  src/api_routes_http.rs
  src/code_migrations.rs
Labels: area: database, area: api, area: auth

#4845 Adding ability to restore content on user unban.
  api_tests/package.json
  api_tests/pnpm-lock.yaml
  api_tests/src/post.spec.ts
  api_tests/src/shared.ts
  crates/api/src/community/ban.rs
  crates/api/src/lib.rs
  crates/api/src/local_user/ban_person.rs
  crates/api/src/site/purge/person.rs
  crates/api_common/src/community.rs
  crates/api_common/src/person.rs
  crates/api_common/src/send_activity.rs
  crates/api_common/src/utils.rs
  crates/apub/src/activities/block/block_user.rs
  crates/apub/src/activities/block/mod.rs
  crates/apub/src/activities/block/undo_block_user.rs
  crates/apub/src/activities/mod.rs
  crates/apub/src/protocol/activities/block/undo_block_user.rs
Labels: breaking change

#4469 Adding a default_comment_sort_type column for local_site and local_user.
  crates/api/src/local_user/save_settings.rs
  crates/api_common/src/community.rs
  crates/api_common/src/person.rs
  crates/api_common/src/post.rs
  crates/api_common/src/site.rs
  crates/api_crud/src/site/create.rs
  crates/api_crud/src/site/update.rs
  crates/apub/src/api/list_comments.rs
  crates/apub/src/api/list_posts.rs
  crates/apub/src/api/mod.rs
  crates/apub/src/api/user_settings_backup.rs
  crates/apub/src/collections/community_outbox.rs
  crates/db_perf/src/main.rs
  crates/db_schema/src/lib.rs
  crates/db_schema/src/schema.rs
  crates/db_schema/src/source/local_site.rs
  crates/db_schema/src/source/local_user.rs
  crates/db_schema/src/utils.rs
  crates/db_views/src/post_view.rs
  crates/db_views/src/registration_application_view.rs
  crates/db_views_actor/src/community_view.rs
  crates/db_views_actor/src/person_view.rs
  crates/routes/src/feeds.rs
  migrations/2024-09-16-000000_default_comment_sort_type/down.sql
  migrations/2024-09-16-000000_default_comment_sort_type/up.sql
Labels: breaking change
